### PR TITLE
Add Gitleaks Timeout Logic and fix multiple bugs found

### LINKED ISSUE #435: GitLeaks takes too long to finish
When running huskyCI on a large project, I came across an issue of GitLeaks taking too long to finish, approximately 23 minutes, as shown by the image below: 

image

I believe we need to code a solution that makes GitLeaks run faster and consequentially make huskyCI's stage faster on the developer's CI.

### PR DESCRIPTION
**Pull request by rafaveira3**
## Closes #435

This PR aims to add a new timeout check in the Gitleaks instructions. By doing that, huskyCI will not fail anymore the whole analysis if this particular securityTest takes too long to finish. The initial timeout set is 5 minutes.

### Changes

* API: Add a new `ERROR_TIMEOUT_GITLEAKS` message check logic.
* Client: Add the `NoSecHusky` output.

### Bugs fixed

* API: Fix `NoSecVulns` output instead of `LowVulns` in `api/securitytest/run.go`.
* API: Log error message in `api/securitytest/enry.go`.
* API: Fix loop when number of nosec is 0 in `api/securitytest/gosec.go`.
* Client: Add an `OR` statement for cases where only `nosec` vulnerabilities are found in `client/analysis/output.go`.

### CODE REVIEW

File: api/securitytest/gitleaks.go [hunk 1]
```diff
@@ -42,6 +42,23 @@ func analyseGitleaks(gitleaksScan *SecTestScanInfo) error {
 		return nil
 	}
 
+	// if gitleaks timeout, a warning will be generated as a low vuln
```
Comment (Krlier) [inline api/securitytest/gitleaks.go]: Would you mind changing this comment to `nohusky vuln`? Reading the rest of the changes, I believe that a warning will be added as a `nohusky vuln`.

File: api/securitytest/gitleaks.go [hunk 2]
```diff
@@ -61,6 +78,29 @@ func (gitleaksScan *SecTestScanInfo) prepareGitleaksVulns() {
 
 	huskyCIgitleaksResults := types.HuskyCISecurityTestOutput{}
 	gitleaksOutput := gitleaksScan.FinalOutput.(GitleaksOutput)
+
+	if gitleaksScan.GitleaksTimeout {
+		gitleaksVuln := types.HuskyCIVulnerability{}
+		gitleaksVuln.Language = "Generic"
+		gitleaksVuln.SecurityTool = "Gitleaks"
+		gitleaksVuln.Severity = "nosec"
+		gitleaksVuln.Details = "It looks like your project is too big and huskyCI was not able to run Gitleaks."
```
Comment (Krlier) [inline api/securitytest/gitleaks.go]: Should we add some instructions on how to run a full Gitleaks analysis? What do you think?
Maybe this detail section could point to a page in the wiki with instructions.

File: api/config.yaml [hunk 3]
```diff
@@ -308,7 +308,8 @@ gitleaks:
     git clone -b %GIT_BRANCH% --single-branch %GIT_REPO% code --quiet 2> /tmp/errorGitCloneGitleaks
     if [ $? -eq 0 ]; then
         touch /tmp/results.json
-        $(which gitleaks) --log=warn --report=/tmp/results.json --repo-path=./code --branch=%GIT_BRANCH% --repo-config > /tmp/errorGitleaks
+        timeout -t 300 $(which gitleaks) --log=warn --report=/tmp/results.json --repo-path=./code --branch=%GIT_BRANCH% --repo-config > /tmp/errorGitleaks ||
```
Comment (Krlier) [inline api/config.yaml]: Should we add this timeout to all other security tests? This way husky would always run in under 5 minutes.

Comment (rafaveira3) [reply api/config.yaml]: Absolutely, @Krlier! I totally agree. Can you create an issue so we can work on this soon, please?

File: api/securitytest/gitleaks.go (hunk 2 above)
Comment (rafaveira3) [reply api/securitytest/gitleaks.go]: Great idea! Can you create an issue so we can work on this guide soon? We could add it into our documentation at [http://husky.ci](http://husky.ci), what do you think?

File: api/securitytest/gitleaks.go (hunk 1 above)
Comment (rafaveira3) [reply api/securitytest/gitleaks.go]: Sure, @Krlier! Good catch. I have fixed it at a3e16ab6d4e98610dd7889acbf4016a30a48593f.

File: api/securitytest/gitleaks.go (hunk 2 above)
Comment (Krlier) [reply api/securitytest/gitleaks.go]: I just created this [issue](https://github.com/globocom/huskyCI/issues/451) so we can work on this guide soon!

File: api/config.yaml (hunk 3 above)
Comment (Krlier) [reply api/config.yaml]: I just created this [issue](https://github.com/globocom/huskyCI/issues/452) so we can work on it later!

File: client/analysis/output.go [hunk 4]
```diff
@@ -164,7 +164,7 @@ func prepareAllSummary(analysis types.Analysis) {
 	outputJSON.Summary.GitleaksSummary.LowVuln = len(outputJSON.GenericResults.HuskyCIGitleaksOutput.LowVulns)
 	outputJSON.Summary.GitleaksSummary.MediumVuln = len(outputJSON.GenericResults.HuskyCIGitleaksOutput.MediumVulns)
 	outputJSON.Summary.GitleaksSummary.HighVuln = len(outputJSON.GenericResults.HuskyCIGitleaksOutput.HighVulns)
```
Comment (Krlier) [inline client/analysis/output.go]: I believe you should update `GitleaksSummary.NosecVuln` with its length here. This way it should output the correct value on line 183.

Comment (rafaveira3) [reply client/analysis/output.go]: Great catch! Thanks a lot for 6023766.

Comment (Krlier) [reply client/analysis/output.go]: Fixed it in [6023766](https://github.com/globocom/huskyCI/pull/450/commits/6023766763a83f8b2286c7f71b2cc5e10b95a775)
