### PR TITLE
Fix Safety warning bug

### LINKED ISSUE #188: Safety output Unmarshall issues
After running huskyCI in a Python project, the following error is being shown:

```
[HUSKYCI] [!]: Warning: unpinned requirement 'Flask' found in safety_analysis_requirements.txt, unable to check.
[HUSKYCI] [!]: Warning: unpinned requirement 'gunicorn' found in safety_analysis_requirements.txt, unable to check.
[HUSKYCI] [!]: Warning: unpinned requirement 'requests' found in safety_analysis_requirements.txt, unable to check.
[HUSKYCI][ERROR] Could not Unmarshal safetyOutput! invalid character 'W' looking for beginning of value
```

### PR DESCRIPTION
**Pull request by rafaveira3**
## Closes #188 

I have added some comments inline to explain these changes.

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -64,6 +64,10 @@ build:
 build-client:
 	cd client/cmd && $(GO) build -o "$(HUSKYCICLIENTBIN)" && mv "$(HUSKYCICLIENTBIN)" ../..
 
+## Builds client to the executable file huskyci-client
+build-client-linux:
```
Comment (rafaveira3) [inline Makefile]: Using `make build` and trying to run it in a linux container returned some errors. Added `build-client-linux` to help people build a linux binary.

File: api/analysis/safety.go [hunk 2]
```diff
@@ -31,18 +31,27 @@ type SafetyIssue struct {
...
 
-	var cResult string
+	var outputJSON string
 	analysisQuery := map[string]interface{}{"containers.CID": CID}
 
-	warningFound := strings.Contains(cOutput, "Warning: unpinned requirement ")
-	if warningFound {
-		tmpcOutput := StringToLastLine(cOutput)
-		cOutput = tmpcOutput
+	requirementsNotFound := strings.Contains(cOutput, "ERROR_REQ_NOT_FOUND")
```
Comment (rafaveira3) [inline api/analysis/safety.go]: First thing we need to do is to check if there were errors in Safety output.

File: api/analysis/safety.go [hunk 3]
```diff
@@ -56,19 +65,40 @@ func SafetyStartAnalysis(CID string, cOutput string) {
 		return
 	}
 
-	// step 1: Unmarshall cOutput into safetyOutput struct.
+	warningFound := strings.Contains(cOutput, "Warning: unpinned requirement ")
```
Comment (rafaveira3) [inline api/analysis/safety.go]: Have we found any warning in safety output?

File: api/analysis/safety.go [hunk 4]
```diff
@@ -56,19 +65,40 @@ func SafetyStartAnalysis(CID string, cOutput string) {
...
 	safetyOutput := SafetyOutput{}
-	err := json.Unmarshal([]byte(cOutput), &safetyOutput)
+	err := json.Unmarshal([]byte(cOutputSanitized), &safetyOutput)
 	if err != nil {
 		log.Error("SafetyStartAnalysis", "SAFETY", 1018, cOutput, err)
 		return
 	}
 
-	// step 1.1: Sets the container output to "No issues found" if SafetyIssues returns an empty slice
-	if len(safetyOutput.SafetyIssues) == 0 && !warningFound {
```
Comment (rafaveira3) [inline api/analysis/safety.go]: This condition was never met. Removing `!warningFound`

File: api/analysis/safety.go [hunk 5]
```diff
@@ -78,42 +108,16 @@ func SafetyStartAnalysis(CID string, cOutput string) {
...
-	scanner := bufio.NewScanner(strings.NewReader(s))
-	for scanner.Scan() {
-		lines = append(lines, scanner.Text())
 	}
-	return lines[len(lines)-1]
-}
+	return
 
-// GetAllLinesButLast receives a string with multiple lines and returns all but the last line.
-func GetAllLinesButLast(s string) []string {
```
Comment (rafaveira3) [inline api/analysis/safety.go]: These utils functions will be place into `util` package as both client and api uses them.

File: api/config.yaml [hunk 6]
```diff
@@ -121,9 +121,9 @@ safety:
     git clone -b %GIT_BRANCH% --single-branch %GIT_REPO% code --quiet 2> /tmp/errorGitCloneSafety
     if [ $? -eq 0 ]; then
       cd code
-      cat *requirements* | grep '=' | grep -v '#' > safety_analysis_requirements.txt 2> /tmp/errorGetRequirements
```
Comment (rafaveira3) [inline api/config.yaml]: Just trying to avoid some misunderstood during CI: "My project does not contain this file!". Adding `huskyci` to it's name may mitigate this a little bit.

File: client/analysis/output.go [hunk 7]
```diff
@@ -37,19 +37,19 @@ func CheckContainerOutput(container types.Container) {
 }
 
 // PrintGosecOutput will print the Gosec output.
-func PrintGosecOutput(containerOutput string) {
```
Comment (rafaveira3) [inline client/analysis/output.go]: Actually client is not analysing the `containerOutput` itself. It is viewing mongoDB field, that was already been handled by huskyCI API.

File: client/analysis/output.go [hunk 8]
```diff
@@ -315,57 +315,62 @@ func PrintBrakemanOutput(containerOutput string) {
...
-		warningOutput := analysis.GetAllLinesButLast(containerOutput)
-		containerOutput = tmpcOutput
-		for _, warning := range warningOutput {
-			color.Yellow("[HUSKYCI] [!]: %s", warning)
-		}
-	}
-
-	if containerOutput == "No issues found." && !warningFound {
-		color.Green("[HUSKYCI][*] Safety :)\n\n")
+	if mongoDBcontainerOutput == "Requirements not found or this project uses latest dependencies." {
```
Comment (rafaveira3) [inline client/analysis/output.go]: With current huskyCI code we can't infer yet if there were errors finding requirements files or the project being analyzed does not set the version of it's dependency.
