### PR TITLE
FIX: GoSec updating wrong info into MongoDB

### LINKED ISSUE #220: Client is not showing low vulns If they are the only issues found  (GoSec)
Steps to reproduce: 

```
make install
```

 ```
$ cat .env
export HUSKYCI_CLIENT_REPO_URL="https://github.com/rafaveira3/fix-huskycibug.git"
export HUSKYCI_CLIENT_REPO_BRANCH="fix/branch-bug"
export HUSKYCI_CLIENT_API_ADDR="http://localhost:8888"
export HUSKYCI_CLIENT_API_USE_HTTPS="false"
```

``` 
$ make run-client
[HUSKYCI][*] fix/branch-bug -> https://github.com/rafaveira3/fix-huskycibug.git
[HUSKYCI][*] HuskyCI analysis started! 6ujMDumpUqnzR4C2zwjcuc1lPZmFVAkr

[HUSKYCI][*] Gosec :)
```

image

### PR DESCRIPTION
**Pull request by rafaveira3**
## Closes #220 

Following the steps to reproduce from the Issue,  the following output is being shown with this modification: 

```
$ make run-client
[HUSKYCI][*] master -> https://github.com/rafaveira3/fix-huskycibug.git
[HUSKYCI][*] HuskyCI analysis started! Zv1MtWiZfre2qBRChM3EPKDBYMFYWQ0p
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...
[HUSKYCI][!] Hold on! HuskyCI is still running...

[HUSKYCI][!] Severity: LOW
[HUSKYCI][!] Confidence: HIGH
[HUSKYCI][!] Details: Errors unhandled.
[HUSKYCI][!] File: /go/src/code/main.go
[HUSKYCI][!] Line: %!d(string=7)
[HUSKYCI][!] Code: word, _ := retornaErro()

[HUSKYCI][*] Gosec :|
```

### CODE REVIEW

File: api/analysis/gosec.go [hunk 1]
```diff
@@ -94,7 +94,7 @@ func GosecStartAnalysis(CID string, cOutput string) {
 	}
 
 	// step 3: update analysis' cResult into AnalyisCollection.
-	issueMessage := "No issues found."
+	issueMessage := "Warning found."
 	if cResult != "passed" {
```
Comment (Krlier) [inline api/analysis/gosec.go]: I think `cResult` will never hold the string `passed`, this way this `if` condition will never be used. Could you please confirm that @rafaveira3 ?

Comment (rafaveira3) [reply api/analysis/gosec.go]: Good observation. If `cOutput` comes empty, no issues were found from Gosec. We will set that [here](https://github.com/globocom/huskyCI/pull/223/files/ced68a1dbd59f274c24e5e7ebe2cbe91c7285c7d#diff-de4cd9ec349b16ef4f6283ce814f34cdR52) and a `return` call we be made. If we ever manage to get until this code here, we can guarantee that warnings were found.

Comment (rafaveira3) [reply api/analysis/gosec.go]: Yes! Good catch, @Krlier ! I have updated this at f22953a , would you mind taking a look at it, please?
